# Generated by Django 4.2.2 on 2023-07-08 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shop',
            new_name='Merch',
        ),
    ]
