# Generated by Django 4.2.2 on 2023-07-11 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_shop_merch'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('img', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=1000)),
                ('high_priority', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='merch',
            name='img',
            field=models.CharField(default=None, max_length=500),
            preserve_default=False,
        ),
    ]
